#!/bin/bash

source setup.sh

docker run --rm -t --name ee4-base --net=host -v ~/.ee4:$EE_HOME/.ee4 -v ~/Sites:$EE_HOME/Sites \
			-v /var/run/docker.sock:/var/run/docker.sock:ro \
			-e HOST_HOME=$EE_HOME -e USER_ID=$USER_ID -e GROUP_ID=$GROUP_ID -e  DOCKER_ID=$DOCKER_ID \
			dharmin/ee4-base $@

